steps:
  # Step to set up Docker Compose
  - name: "docker/compose:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        export POSTGRES_USER=$$POSTGRES_USER
        export POSTGRES_PASSWORD=$$POSTGRES_PASSWORD
        export POSTGRES_DB=$$POSTGRES_DB
        export AWS_ACCESS_KEY_ID=$$AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY=$$AWS_SECRET_ACCESS_KEY
        docker-compose up --build -d
    secretEnv: ['POSTGRES_USER', 'POSTGRES_PASSWORD', 'POSTGRES_DB', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']

# Optionally, specify any secrets or additional configurations
availableSecrets:
  secretManager:
    - versionName: projects/river-tiger-440210-m6/secrets/SPM/versions/latest
      env: "POSTGRES_USER"
      env: "POSTGRES_PASSWORD"
      env: "POSTGRES_DB"
      env: "AWS_ACCESS_KEY_ID"
      env: "AWS_SECRET_ACCESS_KEY"


  logging: CLOUD_LOGGING_ONLY
