steps:
  # Step to set up Docker Compose
  - name: "docker/compose:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        secret=$(gcloud secrets versions access latest --secret=SPM)
        export POSTGRES_USER=$(echo "$secret" | jq -r '.POSTGRES_USER')
        export POSTGRES_PASSWORD=$(echo "$secret" | jq -r '.POSTGRES_PASSWORD')
        export POSTGRES_DB=$(echo "$secret" | jq -r '.POSTGRES_DB')
        export AWS_ACCESS_KEY_ID=$(echo "$secret" | jq -r '.AWS_ACCESS_KEY_ID')
        export AWS_SECRET_ACCESS_KEY=$(echo "$secret" | jq -r '.AWS_SECRET_ACCESS_KEY')
        docker-compose up --build -d
    secretEnv: ['SPM']

# Optionally, specify any secrets or additional configurations
availableSecrets:
  secretManager:
    - versionName: projects/river-tiger-440210-m6/secrets/SPM/versions/latest
      env: "SPM"

options:
  logging: CLOUD_LOGGING_ONLY
