version: "3.9"

services:
#################################
# Database
#################################
  db:
    container_name: db
    build: ./database
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
    driver: local