version: "3.9"

services:
#################################
# Database
#################################
  db:
    container_name: db
    build: ./database
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal_network
#################################
# Authentication
#################################
  authentication:
    container_name: authentication
    build: ./authentication
    ports: 
      - "5001:5001"
    env_file:
      - .env
    networks:
      - internal_network
    environment:
      PYTHONUNBUFFERED: 1
#################################
# Requests
#################################
  requests:
    container_name: requests
    build: ./requests
    ports: 
      - "5002:5002"
    env_file:
      - .env
    networks:
      - internal_network
    environment:
      PYTHONUNBUFFERED: 1
#################################
# RabbitMQ 
#################################
  rabbitmq:
    container_name: amqp
    build: ./amqp
    ports:
      - "15672:15672"  # Expose RabbitMQ management interface
      - "5672:5672"    # Expose RabbitMQ main port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
    networks:
      - internal_network
#################################
# Emailing service
#################################
  emailing:
    build: ./emailing
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - internal_network

volumes:
  pgdata:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  internal_network:
    driver: bridge