version: "3.9"

services:
#################################
# Database
#################################
  db:
    container_name: db
    build: ./database
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal_network
#################################
# Authentication
#################################
  authentication:
    container_name: authentication
    build: ./authentication
    ports: 
      - "5001:5001"
    env_file:
      - .env
    networks:
      - internal_network
    environment:
      PYTHONUNBUFFERED: 1
#################################
# Requests
#################################
  requests:
    container_name: requests
    build: ./requests
    ports: 
      - "5002:5002"
    env_file:
      - .env
    networks:
      - internal_network
    environment:
      PYTHONUNBUFFERED: 1


volumes:
  pgdata:
    driver: local

networks:
  internal_network:
    driver: bridge