name: CI for Python Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build the Docker image using the path to docker-compose.yml
      - name: Build Docker image
        run: docker-compose -f backend/docker-compose.yml build

      # Run the tests within the Docker container using the path to docker-compose.yml
      - name: Run unit tests
        run: |
          docker-compose -f backend/docker-compose.yml run --rm requests pytest backend/requests/unit_tests.py --maxfail=1 --disable-warnings -q
